version: "3"
services:
  app:
    container_name: feelingsbingo
    restart: unless-stopped
    build: .
    env_file:
      - ./.env
    links:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email pjbrof@gmail.com --agree-tos --no-eff-email --staging -d feelingsbingo.com  -d www.feelingsbingo.com
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/node/feelings-bingo/public/
      o: bind
networks:
  app-network:
    driver: bridge
