version: '3'
services:
  app:
    container_name: feelingsbingo
    restart: always
    build: .
    env_file:
      - ./.env
    ports:
      - 80:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
