GET http://localhost:3000/

###

POST http://localhost:3000/newgame

###

GET http://localhost:3000/6FZtKoIE0


###

DELETE http://localhost:3000/endgame/_t-IbnxgM

###

PATCH http://localhost:3000/6FZtKoIE0
Content-Type: application/json

{
    "counter": 1,
    "player": "Patrick"
}