GET http://localhost:3000/api/v1/games

###

POST http://localhost:3000/api/v1/newgame

###

GET http://localhost:3000/api/v1/joingame/UbOZra5a-
###

DELETE http://localhost:3000/api/v1/endgame/0GXAJ87No

###

DELETE http://localhost:3000/api/v1/purge
